version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '13:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  groups:
    production-dependencies:
      dependency-type: "production"
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
    development-dependencies:
      dependency-type: "development"
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
