version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm ci
            - npm run build
    build:
        commands:
            - npm test
            - npm run test_conditions
            - npm run verdaccio
