version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: nodejs10
      buildspec: codebuild/nodejs10.yml
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
    - identifier: nodejs12
      buildspec: codebuild/nodejs12.yml
      env:
        image: aws/codebuild/standard:5.0
        compute-type: BUILD_GENERAL1_MEDIUM
