version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: testNodejs20
      buildspec: codebuild/nodejs20.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testNodejs18
      buildspec: codebuild/nodejs18.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testNodejs16
      buildspec: codebuild/nodejs16.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testBrowser18
      buildspec: codebuild/browser18.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: compliance
      buildspec: codebuild/compliance.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejs16
      buildspec: codebuild/test_vectors/nodejs16.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejs18
      buildspec: codebuild/test_vectors/nodejs18.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejs20
      buildspec: codebuild/test_vectors/nodejs20.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsBrowser18
      buildspec: codebuild/test_vectors/browser18.yml
      env:
        variables:
          PUBLISH_LOCAL: "true"
        image: aws/codebuild/standard:5.0
