version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: testNodejsLatest
      buildspec: codebuild/nodejs_latest.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testNodejs14
      buildspec: codebuild/nodejs14.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testNodejs16
      buildspec: codebuild/nodejs16.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testBrowser
      buildspec: codebuild/browser.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: compliance
      buildspec: codebuild/compliance.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejsLatest
      buildspec: codebuild/test_vectors/nodejs_latest.yml
      env:
        variables:
          PUBLISH_LOCAL: "true"
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejs14
      buildspec: codebuild/test_vectors/nodejs14.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsNodejs16
      buildspec: codebuild/test_vectors/nodejs16.yml
      env:
        image: aws/codebuild/standard:5.0
    - identifier: testVectorsBrowser
      buildspec: codebuild/test_vectors/browser.yml
      env:
        variables:
          PUBLISH_LOCAL: "true"
        image: aws/codebuild/standard:5.0
