version: 0.2

batch:
  fast-fail: true 
  build-graph:
# CI
    - identifier: nodejs12
      buildspec: codebuild/nodejs12.yml
      env:
        image: aws/codebuild/standard:5.0
        compute-type: BUILD_GENERAL1_MEDIUM

# Version the project and push git commits and tags
    - identifier: version
      depend-on:
        - nodejs10
        - nodejs12
      buildspec: codebuild/release/version.yml
      env:
        image: aws/codebuild/standard:5.0

# Publish the release to npm
    - identifier: publish
      depend-on:
        - version
      buildspec: codebuild/release/publish.yml
      env:
        image: aws/codebuild/standard:5.0
