version: 0.2

batch:
  fast-fail: true 
  build-graph:

# Lint and specification compliance
    - identifier: compliance
      buildspec: codebuild/compliance.yml

# Unit Tests
    - identifier: testNodejs16
      buildspec: codebuild/nodejs16.yml
      env:
        image: aws/codebuild/standard:5.0

# Integration Tests
    - identifier: testVectorsNodejs16
      buildspec: codebuild/test_vectors/nodejs16.yml
      env:
        variables:
          PUBLISH_LOCAL: "true"
        image: aws/codebuild/standard:5.0

# Version the project and push git commits and tags
    - identifier: version
      depend-on:
        - compliance
        - testNodejs16
        - testVectorsNodejs16
      buildspec: codebuild/release/version.yml
      env:
        image: aws/codebuild/standard:6.0

# Publish the release to npm
    - identifier: publish
      depend-on:
        - version
      buildspec: codebuild/release/publish.yml
      env:
        image: aws/codebuild/standard:6.0

# Validate that the published versions are available
    - identifier: validateNodejs
      depend-on:
        - publish
      buildspec: codebuild/test_vectors/nodejs16.yml
      env:
        variables:
          PUBLISH_LOCAL: "false"
        image: aws/codebuild/standard:5.0
